import { auth } from "@/auth";
import TailwindInAntdLayout from "@/components/layout/TailwindInAntdLayout";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { dir } from "i18next";
import { languages } from "@/i18n/settings";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
// get font from google
const inter = Inter({ subsets: ["latin"] });
// metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// layout for the page
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { language: string };
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang={params.language} dir={dir(params.language)}>
        <body className={inter.className}>
          <TailwindInAntdLayout> {children}</TailwindInAntdLayout>
        </body>
      </html>
    </SessionProvider>
  );
}
